* Converting to A-Normal form with delimited continuations
Embarassingly, I found myself struggling to write down a function that
converts lambda terms to their A-Normal Forms. I vaguely remember that
the conversion requires defining the evaluation context. Before I
started implementing it, I realized that I could skip the process of
reifying continuations to evaluation contexts if the language
supports delimited continuations natively!

Following [[https://matt.might.net/articles/a-normalization/][the Racket CPS-style implementation]] by Matt Might (which is
ultimately based on Flanagan et al.'s scheme implementation), I wrote
an ANF conversion algorithm in Racket for a simple language with arithmetic
operations and let bindings, using the =shift= and =prompt=
primitives from the Racket standard library.

I've always had trouble understanding functions written in CPS style,
and oddly enough, converting it to direct style with delimited
continuations somehow made the algorithm much easier to understand for
me.
